name: Generating The Midnight docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: generated-docs
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version: '26'
      - name: Install elm
        run: npm install --global elm@0.19.1
      - name: Fetch main
        run: |
          git fetch origin main
      - name: Reset generated-docs to main
        run: |
          git reset --hard origin/main
      - name: Merge main
        run: |
          git merge origin/main --no-edit
      - name: Compile with elm
        run: |
          ./compile.sh
      - name: Force add generated file
        run: |
          git add -f elm.js
          git commit -m "Merge main and add elm.js from Github CI" || echo "No changes to commit"
          git push -f
